use crate::enum_builder;
use rand::prelude::IndexedRandom;
use rand::rng;
use serde::Deserialize;

enum_builder! {
    #[repr(u16)]
    #[derive(Deserialize)]
    pub enum ActorId {
        EntryPoint1 = 1,
        EntryPoint2 = 2,
        Bigbutt = 4,
        Ticker = 5,
        Grublin = 6,
        Conga = 8,
        MumbosMountainMudHut = 9,
        ShockJumpPad = 11,
        Chimpy = 15,
        JuJu = 17,
        Beehive = 18,
        EntryPoint3 = 21,
        Leaky = 30,
        PumpkinTransformation = 32,
        CrocodileTransformation = 33,
        WalrusTransformation = 34,
        BeeTransformation = 34,
        MmmFlowerPot = 37,
        ChimpysOrange = 41,
        BlubbersGold = 42,
        TurboTrainers = 44,
        MumboToken = 45,
        Jiggy = 70,
        EmptyHoneycomb = 71,
        ExtraLife = 73,
        BlueEggActor = 82,
        RedCross1 = 85,
        Shrapnel = 86,
        OrangePad = 87,
        YellowJinjo = 94,
        OrangeJinjo = 95,
        BlueJinjo = 96,
        PinkJinjo = 97,
        GreenJinjo = 98,
        WadingBoots = 101,
        Snippet = 103,
        YumYum = 105,
        EntryPoint16 = 115,
        EntryPoint15 = 116,
        EntryPoint14 = 117,
        EntryPoint4 = 118,
        EntryPoint5 = 119,
        EntryPoint6 = 120,
        EntryPoint7 = 121,
        EntryPoint8 = 122,
        EntryPoint10 = 124,
        EntryPoint12 = 126,
        Ripper = 199,
        TeeHee = 202,
        FlightPad = 228,
        EntryPoint18 = 259,
        EntryPoint19 = 260,
        EntryPoint20 = 261,
        Blubber = 277,
        Nipper = 279,
        Slappa = 288,
        SirSlush = 292,
        SpiralMountainBottlesMolehill = 299,
        Gobi1 = 302,
        GobisRock = 304,
        Gobi2 = 305,
        RedFlibbit = 307,
        Buzzbomb = 308,
        Gobi3 = 309,
        Flotsam = 315,
        LighthouseDoor = 318,
        SunSwitch = 319,
        SunDoor = 320,
        StarSwitch = 324,
        GvHoneycombSwitch = 325,
        BreegullTarget = 326,
        Lockup1 = 337,
        Lockup2 = 338,
        Lockup3 = 339,
        Nibbly = 355,
        TutorialColliwobble = 356,
        TutorialBawl = 357,
        TutorialTopper = 358,
        ColliwobbleWithHoneycomb = 359,
        Quarrie = 367,
        PlayerForceWalk = 389,
        JiggyCcWitchSwitch = 400,
        Grimlet = 454,
        GrilleChompa = 460,
        CollectableBluePresent = 493,
        CollectableGreenPresent = 495,
        CollectableRedPresent = 497,
        RingCactus = 505,
        WitchSwitchMumbosMountain = 516,
        JiggyMmWitchSwitch = 517,
        WitchSwitchMadMonsterMansion = 518,
        JiggyMmmWitchSwitch = 519,
        JiggyTtcWitchSwitch = 521,
        WitchSwitchRustyBucketBay = 523,
        JiggyRbbWitchSwitch = 524,
        LairCcLobbyGrate = 531,
        LairCcLobbyGrateSwitch = 532,
        SnowRoofHouse = 553,
        JiggyCcwWitchSwitch = 568,
        SharkfoodIsland = 604,
        BetaVent = 649,
        BigClucker = 671,
        Caterpillar = 674,
        NabnutsAcorn = 681,
        Lighthouse = 738,
        WorldSign = 739,
        WorldStartPad = 740,
        BoomBox = 781,
        KingSandybuttsPyramid = 797,
        Brentilda = 840,
        BeeSwarm = 845,
        Limbo = 846,
        MumMum = 847,
        SeamanGrublin = 848,
        RedGruntling = 871,
        Colliwobble = 877,
        Bawl = 878,
        Topper = 879,
        GrublinHood = 885,
        GlobalBottlesMolehill = 890,
        Chinker = 893,
        Scabby = 896,
        PortraitChompa = 897,
        Igloo = 942,
        Chimney = 944,
        SpiralMountainBridgeForcedMovementStart = 957,
        SpiralMountainBridgeForcedMovementTarget = 958,
        BlueGruntling = 959,
        BlackGruntling = 960,
    }
}

const ENEMIES: [ActorId; 22] = [
    ActorId::Bigbutt,
    ActorId::Ticker,
    ActorId::Grublin,
    ActorId::Snippet,
    ActorId::YumYum,
    ActorId::Ripper,
    ActorId::TeeHee,
    ActorId::RedFlibbit,
    ActorId::Flotsam,
    ActorId::Grimlet,
    ActorId::Limbo,
    ActorId::MumMum,
    ActorId::SeamanGrublin,
    ActorId::RedGruntling,
    ActorId::Colliwobble,
    ActorId::Bawl,
    ActorId::Topper,
    ActorId::GrublinHood,
    ActorId::Chinker,
    ActorId::Scabby,
    ActorId::BlueGruntling,
    ActorId::BlackGruntling,
];

impl ActorId {
    pub fn needs_flag(&self) -> bool {
        match self {
            Self::Jiggy => true,
            Self::MumboToken => true,
            Self::EmptyHoneycomb => true,
            _ => false,
        }
    }

    pub fn can_globalize(&self) -> bool {
        match self {
            ActorId::ChimpysOrange => true,
            _ => false,
        }
    }

    pub fn is_enemy(&self) -> bool {
        ENEMIES.contains(self)
    }

    pub fn random_enemy() -> Self {
        *ENEMIES.choose(&mut rng()).unwrap()
    }
}
